Numpy&Pandas

In [21]:
import numpy as np
import pandas as pd

In [5]:
#构造向量和矩阵
vector = numpy.array([5, 10, 15, 20])
matrix = numpy.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print (vector)
print (matrix)

[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [6]:
#矩阵切片
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[1:3,0:2])

[[20 25]
 [35 40]]


In [8]:
#条件筛选
matrix = numpy.array([
            [5, 10, 15], 
            [20, 25, 30],
            [35, 40, 45]
         ])
second_column_25 = matrix[:,1] == 25
print (second_column_25)
matrix[second_column_25, 1] = 10
print (matrix)

[False  True False]
[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


In [11]:
#矩阵乘法
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
print (A)
print (B)
print (A*B)
print (A.dot(B))
print (np.dot(A, B)) 

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [12]:
# 8*8棋盘矩阵，其中1、3、5、7行&&0、2、4、6列的元素置为1   1 ,3，5，7列&&0,2,4,6行也是1
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print (z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [14]:
#归一化，将矩阵规格化到0～1，即最小的变成0，最大的变成1，最小与最大之间的等比缩放
z = 10*np.random.random((5,5))
print (z)
zmin,zmax = z.min(),z.max()
z = (z-zmin)/(zmax-zmin)
print (z.round(2))

[[2.53701745 6.32441088 4.27908261 9.5399459  9.45851467]
 [0.62967281 9.28610955 1.41546268 0.26367098 9.42115068]
 [1.06281355 1.12124388 8.69246063 8.37476577 3.31466275]
 [6.06726723 8.28284048 9.99266786 5.43277489 3.47624078]
 [5.86309673 2.72509156 2.80342883 8.68209757 9.0825703 ]]
[[0.23 0.62 0.41 0.95 0.95]
 [0.04 0.93 0.12 0.   0.94]
 [0.08 0.09 0.87 0.83 0.31]
 [0.6  0.82 1.   0.53 0.33]
 [0.58 0.25 0.26 0.87 0.91]]


In [15]:
#交换矩阵的其中两行
a = np.arange(25).reshape(5,5)
print (a)
a[[0,1]] = a[[1,0]]
print (a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [17]:
#找出数组中与给定值最接近的数
z = np.array([[0,1,2,3],[4,5,6,7]])
a = 5.1
print (np.abs(z-a).argmin())

5


In [20]:
#生成二维的高斯矩阵
x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
print (x)
print (y)
D = np.sqrt(x**2+y**2)
print (D)
sigma,mu = 1,0
a = np.exp(-(D-mu)**2/(2*sigma**2))
print (a)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


In [ ]:
# 按某列的值排序
food_info.sort_values("Sodium_(mg)", inplace=True, ascending=False)

In [ ]:
# 对每列运行某函数
hundredth_row = titanic_survival.apply(hundredth_row)

In [ ]:
# 重设索引
sorted_by_index = series_custom.reindex(sorted_index)

In [ ]:
# 过滤值只为float类型
float_columns = types[types.values == 'float64'].index
float_df = fandango_films[float_columns]